# Site settings
title: Zhao Li's Page
description: A blog about Zhao Li
# baseurl: "/particle" # the subpath of your site, e.g. /blog
url: "hl1028.github.io" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Zhao Li
user_description: First year graduate student at University of Pennsylvania, studying computer science in the program Master of Computer and Information Technology. <br>Embrace all opportunities from tech companies and tech-related positions at finance companies especially software development engineer internship. <br>Feel free to contact me through <a href="mailto: harry28@seas.upenn.edu">harry28@seas.upenn.edu</a>
user_title: Software Developer
email: harry28@seas.upenn.edu
#twitter_username: lorem_ipsum
github_username:  hl1028
#gplus_username:  lorem_ipsum

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
